# Generated by Django 5.2.7 on 2025-10-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(max_length=200)),
                ('district_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('district_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['state_name', 'district_name'],
            },
        ),
        migrations.CreateModel(
            name='MgnregaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('total_jobcards_issued', models.BigIntegerField(blank=True, null=True)),
                ('total_active_job_cards', models.BigIntegerField(blank=True, null=True)),
                ('total_active_workers', models.BigIntegerField(blank=True, null=True)),
                ('total_workers', models.BigIntegerField(blank=True, null=True)),
                ('total_households', models.BigIntegerField(blank=True, null=True)),
                ('total_individuals', models.BigIntegerField(blank=True, null=True)),
                ('total_exp_lakhs', models.FloatField(blank=True, null=True)),
                ('wages_lakhs', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.district')),
            ],
            options={
                'ordering': ['district', '-fetched_at'],
                'indexes': [models.Index(fields=['district', 'fin_year', 'month'], name='dashboard_m_distric_622dd9_idx')],
                'unique_together': {('district', 'fin_year', 'month')},
            },
        ),
    ]
